# -*- coding: utf-8 -*-
"""Recruitment_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hYdIqP-CCx2F6LSCLE-zSKhoqEJ3atD
"""

import streamlit as st
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

# ======================
# TITLE
# ======================
st.title("Recruitment Dashboard")

# ======================
# CONNECT TO BIGQUERY
# ======================
credentials = service_account.Credentials.from_service_account_info(
    st.secrets["gcp_service_account"]
)

client = bigquery.Client(
    credentials=credentials,
    project="recruitment-ptdh"
)

# ======================
# QUERY FUNCTION (BIAR CEPAT)
# ======================
@st.cache_data
def load_data():
    query = """
    SELECT *
    FROM `recruitment-ptdh.recruitment_ptdh.master_rec`
    WHERE candidate_id IS NOT NULL
    """
    return client.query(query).to_dataframe()

df = load_data()

# ======================
# CLEANING DATE
# ======================
date_cols = [
    'start_prf_routing', 'complete_prf_routing', 'start_screening_cv',
    'complete_screening_cv','start_interview_hr','complete_interview_hr',
    'start_interview_user','complete_interview_user','start_psychotest',
    'complete_psychotest','start_offering','ol_sent_to_candidate',
    'complete_offering','start_mcu','mcu_date','mcu_issue_date',
    'start_review_mcu','sent_mcu_to_doctor','review_mcu',
    'start_fu_mcu','complete_fu_mcu','date_fit','date_onboarding'
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

# ======================
# DISPLAY DATA
# ======================
st.subheader("Raw Data")
st.dataframe(df)

# ======================
# FILTER
# ======================
st.subheader("Filter Data")

level = st.selectbox(
    "Select Level",
    sorted(df['level'].dropna().unique())
)

filtered_df = df[df['level'] == level]

st.dataframe(filtered_df)

# ======================
# KPI SIMPLE
# ======================
st.subheader("Summary")

st.metric("Total Candidate", len(df))
st.metric("Filtered Candidate", len(filtered_df))
