# -*- coding: utf-8 -*-
"""Recruitment_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hYdIqP-CCx2F6LSCLE-zSKhoqEJ3atD
"""

from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

# Buat BigQuery client
project_id = 'recruitment-ptdh.recruitment_ptdh'
client = bigquery.Client(project = project_id)

!pip install pandas-gbq

import pandas as pd
from google.cloud import bigquery

client = bigquery.Client(project="recruitment-ptdh")

query = """
SELECT *
FROM `recruitment-ptdh.recruitment_ptdh.master_rec`
WHERE candidate_id IS NOT NULL
"""

master_rec = client.query(query).to_dataframe()

master_rec.head()

master_rec.info()

master_rec['start_prf_routing']=pd.to_datetime(master_rec['start_prf_routing'])

cols = ['start_prf_routing', 'complete_prf_routing', 'start_screening_cv','complete_screening_cv','start_interview_hr','complete_interview_hr','start_interview_user','complete_interview_user','start_psychotest','complete_psychotest','start_offering','ol_sent_to_candidate','complete_offering','start_mcu','mcu_date','mcu_issue_date','start_review_mcu','sent_mcu_to_doctor','review_mcu','start_fu_mcu','complete_fu_mcu','date_fit','date_onboarding']

for col in cols:
    master_rec[col] = pd.to_datetime(master_rec[col])

master_rec.info()

display(master_rec)

pip install streamlit

import streamlit as st
st.title("Recruitment Database")
st.dataframe(master_rec)

level = st.selectbox("Filter Level", master_rec['level'].unique())

filtered = master_rec[master_rec['level'] == level]

st.dataframe(filtered)

